// <auto-generated />
using System;
using Cuidexa.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cuidexa.Web.Migrations
{
    [DbContext(typeof(CuidexaDbContext))]
    [Migration("20260923095033_DocumentosFirmados")]
    partial class DocumentosFirmados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cuidexa.Web.Models.Alergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Alergias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Frutos secos",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Lactosa",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Gluten",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CambioTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoSolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoSustitutoPropuestoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoSolicitanteId");

                    b.HasIndex("EmpleadoSustitutoPropuestoId");

                    b.HasIndex("ResueltoPorId");

                    b.ToTable("CambiosTurno");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Centro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ComunidadAutonoma")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsableCargo")
                        .HasColumnType("text");

                    b.Property<string>("ResponsableNombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Centros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "DEMO",
                            FechaCreacion = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Centro Demo",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CuentaDispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CentroId", "Nombre")
                        .IsUnique();

                    b.ToTable("CuentasDispositivo");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Dietas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dieta estándar",
                            Nombre = "Normal",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Textura modificada",
                            Nombre = "Triturada",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Control de azúcares",
                            Nombre = "Diabética",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.DocumentoFirmado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoRegistraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaImagenBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmanteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmanteRelacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IncidenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoRegistraId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("DocumentosFirmados");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EspecialidadId")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlantillaTurnoDefectoId")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("PlantillaTurnoDefectoId");

                    b.HasIndex("CentroId", "Email")
                        .IsUnique();

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CentroId = 1,
                            Email = "admin@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Admin Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CentroId = 1,
                            Email = "cocina@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Cocina Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CentroId = 1,
                            Email = "auxiliar@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Auxiliar Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CentroId = 1,
                            Email = "direccion@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Direccion Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 3
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CentroId = 1,
                            Email = "enfermeria@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Enfermeria Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 4
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CentroId = 1,
                            Email = "profesional@demo.local",
                            EspecialidadId = 1,
                            IntentosFallidos = 0,
                            Nombre = "Fisioterapia Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 5
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CentroId = 1,
                            Email = "limpieza@demo.local",
                            IntentosFallidos = 0,
                            Nombre = "Limpieza Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 6
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fisioterapia",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Logopedia",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Terapia ocupacional",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Psicología",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoDestinoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoOrigenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int?>("RolDestino")
                        .HasColumnType("integer");

                    b.Property<int?>("RolOrigen")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.Property<bool>("Urgente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoDestinoId");

                    b.HasIndex("EmpleadoOrigenId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("EventosDistribucion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId", "Fecha")
                        .IsUnique();

                    b.ToTable("Feriados");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.GrupoNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.ToTable("GruposNotificacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.GrupoNotificacionEmpleado", b =>
                {
                    b.Property<int>("GrupoNotificacionId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.HasKey("GrupoNotificacionId", "EmpleadoId");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("GruposNotificacionEmpleados");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CentroId = 1,
                            Numero = "101",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 2,
                            CentroId = 1,
                            Numero = "102",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 3,
                            CentroId = 1,
                            Numero = "201",
                            Planta = "Planta 2"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Caracter")
                        .HasColumnType("integer");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gravedad")
                        .HasColumnType("integer");

                    b.Property<string>("NotasResolucion")
                        .HasColumnType("text");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("RolOrigen")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoOrigenId");

                    b.HasIndex("ResidenteId");

                    b.HasIndex("ResueltoPorId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Medicaciones");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorAcento")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoRuta")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            FechaCreacion = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuidexa"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Patologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Patologias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Presión arterial elevada",
                            Nombre = "Hipertensión",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Control de glucosa en sangre",
                            Nombre = "Diabetes tipo 2",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Deterioro cognitivo",
                            Nombre = "Alzheimer",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Desgaste articular",
                            Nombre = "Artrosis",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.PlantillaTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("PlantillasTurno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            HoraFin = new TimeOnly(15, 0, 0),
                            HoraInicio = new TimeOnly(7, 0, 0),
                            Nombre = "Mañana",
                            OrganizacionId = 1,
                            TipoDia = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            HoraFin = new TimeOnly(23, 0, 0),
                            HoraInicio = new TimeOnly(15, 0, 0),
                            Nombre = "Tarde",
                            OrganizacionId = 1,
                            TipoDia = 0
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            HoraFin = new TimeOnly(7, 0, 0),
                            HoraInicio = new TimeOnly(23, 0, 0),
                            Nombre = "Noche",
                            OrganizacionId = 1,
                            TipoDia = 0
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.RegistroAdministracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MedicacionId");

                    b.ToTable("RegistrosAdministracion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactoEmergenciaEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaRelacion")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EquipamientoEspecial")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Movilidad")
                        .HasColumnType("integer");

                    b.Property<bool>("NecesitaAyudaLevantarse")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("TipoResidente")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("AlergiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.HasKey("ResidenteId", "AlergiaId");

                    b.HasIndex("AlergiaId");

                    b.HasIndex("CentroId");

                    b.ToTable("ResidenteAlergias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("DietaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("ResidenteDietas");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidentePatologia", b =>
                {
                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("PatologiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("ResidenteId", "PatologiaId");

                    b.HasIndex("CentroId");

                    b.HasIndex("PatologiaId");

                    b.ToTable("ResidentePatologias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SesionTerapia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("SesionesTerapia");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SuperAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SuperAdmins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "superadmin@cuidexa.local",
                            IntentosFallidos = 0,
                            Nombre = "SuperAdmin",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SuscripcionPush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("SuscripcionesPush");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.TareaLimpieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("TareasLimpieza");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoOriginalId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCambio")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsReemplazo")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoReemplazo")
                        .HasColumnType("text");

                    b.Property<string>("NombreExterno")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int?>("PlantillaTurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EmpleadoOriginalId");

                    b.HasIndex("PlantillaTurnoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Vacacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncluyeFinesSemanaYFestivos")
                        .HasColumnType("boolean");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ResueltoPorId");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Alergia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.AuditLog", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Centro");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CambioTurno", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoSolicitante")
                        .WithMany()
                        .HasForeignKey("EmpleadoSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoSustitutoPropuesto")
                        .WithMany()
                        .HasForeignKey("EmpleadoSustitutoPropuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Empleado", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Centro");

                    b.Navigation("EmpleadoSolicitante");

                    b.Navigation("EmpleadoSustitutoPropuesto");

                    b.Navigation("ResueltoPor");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Centro", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany("Centros")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CuentaDispositivo", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Dieta", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.DocumentoFirmado", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoRegistra")
                        .WithMany()
                        .HasForeignKey("EmpleadoRegistraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Incidencia", "Incidencia")
                        .WithMany("DocumentosFirmados")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Centro");

                    b.Navigation("EmpleadoRegistra");

                    b.Navigation("Incidencia");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Empleado", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId");

                    b.HasOne("Cuidexa.Web.Models.PlantillaTurno", "PlantillaTurnoDefecto")
                        .WithMany()
                        .HasForeignKey("PlantillaTurnoDefectoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Centro");

                    b.Navigation("Especialidad");

                    b.Navigation("PlantillaTurnoDefecto");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Especialidad", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoDestino")
                        .WithMany()
                        .HasForeignKey("EmpleadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoOrigen")
                        .WithMany()
                        .HasForeignKey("EmpleadoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Eventos")
                        .HasForeignKey("ResidenteId");

                    b.Navigation("Centro");

                    b.Navigation("EmpleadoDestino");

                    b.Navigation("EmpleadoOrigen");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Feriado", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.GrupoNotificacion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.GrupoNotificacionEmpleado", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.GrupoNotificacion", "GrupoNotificacion")
                        .WithMany("Miembros")
                        .HasForeignKey("GrupoNotificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("GrupoNotificacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Incidencia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoOrigen")
                        .WithMany()
                        .HasForeignKey("EmpleadoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Empleado", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Centro");

                    b.Navigation("EmpleadoOrigen");

                    b.Navigation("Residente");

                    b.Navigation("ResueltoPor");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Medicaciones")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Patologia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.PlantillaTurno", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.RegistroAdministracion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("Cuidexa.Web.Models.Medicacion", "Medicacion")
                        .WithMany("Registros")
                        .HasForeignKey("MedicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("Medicacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Residentes")
                        .HasForeignKey("HabitacionId");

                    b.Navigation("Centro");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Alergia", "Alergia")
                        .WithMany()
                        .HasForeignKey("AlergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Alergias")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alergia");

                    b.Navigation("Centro");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Dieta", "Dieta")
                        .WithMany()
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Dietas")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Dieta");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidentePatologia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Patologia", "Patologia")
                        .WithMany()
                        .HasForeignKey("PatologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Patologias")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Patologia");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SesionTerapia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("SesionesTerapia")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SuscripcionPush", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.TareaLimpieza", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Tareas")
                        .HasForeignKey("HabitacionId");

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Turno", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoOriginal")
                        .WithMany()
                        .HasForeignKey("EmpleadoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.PlantillaTurno", "PlantillaTurno")
                        .WithMany()
                        .HasForeignKey("PlantillaTurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("EmpleadoOriginal");

                    b.Navigation("PlantillaTurno");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Vacacion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Centro");

                    b.Navigation("Empleado");

                    b.Navigation("ResueltoPor");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.GrupoNotificacion", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Navigation("Residentes");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Incidencia", b =>
                {
                    b.Navigation("DocumentosFirmados");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Organizacion", b =>
                {
                    b.Navigation("Centros");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Dietas");

                    b.Navigation("Eventos");

                    b.Navigation("Medicaciones");

                    b.Navigation("Patologias");

                    b.Navigation("SesionesTerapia");
                });
#pragma warning restore 612, 618
        }
    }
}
