// <auto-generated />
using System;
using Cuidexa.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cuidexa.Web.Migrations
{
    [DbContext(typeof(CuidexaDbContext))]
    [Migration("20260911132414_Fase5Turnos")]
    partial class Fase5Turnos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cuidexa.Web.Models.Alergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alergias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Frutos secos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Lactosa"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Gluten"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CambioTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoSolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoSustitutoPropuestoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoSolicitanteId");

                    b.HasIndex("EmpleadoSustitutoPropuestoId");

                    b.HasIndex("ResueltoPorId");

                    b.HasIndex("TurnoId");

                    b.ToTable("CambiosTurno");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dietas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dieta estándar",
                            Nombre = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Textura modificada",
                            Nombre = "Triturada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Control de azúcares",
                            Nombre = "Diabética"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EspecialidadId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@demo.local",
                            Nombre = "Admin Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "cocina@demo.local",
                            Nombre = "Cocina Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "auxiliar@demo.local",
                            Nombre = "Auxiliar Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "direccion@demo.local",
                            Nombre = "Direccion Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 3
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Email = "enfermeria@demo.local",
                            Nombre = "Enfermeria Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 4
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Email = "profesional@demo.local",
                            EspecialidadId = 1,
                            Nombre = "Fisioterapia Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 5
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Email = "limpieza@demo.local",
                            Nombre = "Limpieza Demo",
                            PasswordHash = "$2a$11$VQE3kVBg8hch1ktvqgajiuF46YhG/qf7QOIEotN6q3cMsiNfBO5Pm",
                            Rol = 6
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fisioterapia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Logopedia"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Terapia ocupacional"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Psicología"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("RolDestino")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("EventosDistribucion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "101",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 2,
                            Numero = "102",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 3,
                            Numero = "201",
                            Planta = "Planta 2"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Medicaciones");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Patologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patologias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Presión arterial elevada",
                            Nombre = "Hipertensión"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Control de glucosa en sangre",
                            Nombre = "Diabetes tipo 2"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Deterioro cognitivo",
                            Nombre = "Alzheimer"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Desgaste articular",
                            Nombre = "Artrosis"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.RegistroAdministracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MedicacionId");

                    b.ToTable("RegistrosAdministracion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaRelacion")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EquipamientoEspecial")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Movilidad")
                        .HasColumnType("integer");

                    b.Property<bool>("NecesitaAyudaLevantarse")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("TipoResidente")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("AlergiaId")
                        .HasColumnType("integer");

                    b.HasKey("ResidenteId", "AlergiaId");

                    b.HasIndex("AlergiaId");

                    b.ToTable("ResidenteAlergias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("ResidenteDietas");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidentePatologia", b =>
                {
                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("PatologiaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("ResidenteId", "PatologiaId");

                    b.HasIndex("PatologiaId");

                    b.ToTable("ResidentePatologias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SesionTerapia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("SesionesTerapia");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.TareaLimpieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("TareasLimpieza");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreExterno")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.AuditLog", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.CambioTurno", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoSolicitante")
                        .WithMany()
                        .HasForeignKey("EmpleadoSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Empleado", "EmpleadoSustitutoPropuesto")
                        .WithMany()
                        .HasForeignKey("EmpleadoSustitutoPropuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Empleado", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Turno", "Turno")
                        .WithMany("Cambios")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoSolicitante");

                    b.Navigation("EmpleadoSustitutoPropuesto");

                    b.Navigation("ResueltoPor");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Empleado", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Eventos")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Medicaciones")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.RegistroAdministracion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("Cuidexa.Web.Models.Medicacion", "Medicacion")
                        .WithMany("Registros")
                        .HasForeignKey("MedicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Medicacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Residentes")
                        .HasForeignKey("HabitacionId");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Alergia", "Alergia")
                        .WithMany()
                        .HasForeignKey("AlergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Alergias")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alergia");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Dieta", "Dieta")
                        .WithMany()
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Dietas")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidentePatologia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Patologia", "Patologia")
                        .WithMany()
                        .HasForeignKey("PatologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Patologias")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patologia");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.SesionTerapia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("SesionesTerapia")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.TareaLimpieza", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cuidexa.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Tareas")
                        .HasForeignKey("HabitacionId");

                    b.Navigation("Empleado");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Turno", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Navigation("Residentes");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Medicacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Dietas");

                    b.Navigation("Eventos");

                    b.Navigation("Medicaciones");

                    b.Navigation("Patologias");

                    b.Navigation("SesionesTerapia");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Turno", b =>
                {
                    b.Navigation("Cambios");
                });
#pragma warning restore 612, 618
        }
    }
}
