// <auto-generated />
using System;
using Cuidexa.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cuidexa.Web.Migrations
{
    [DbContext(typeof(CuidexaDbContext))]
    [Migration("20260910161556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cuidexa.Web.Models.Alergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alergias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Frutos secos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Lactosa"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Gluten"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dietas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dieta estándar",
                            Nombre = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Textura modificada",
                            Nombre = "Triturada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Control de azúcares",
                            Nombre = "Diabética"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@demo.local",
                            Nombre = "Admin Demo",
                            PasswordHash = "7DBB7F051B44D7D54584A7BC6C32F00DA5A3B5E6973485B9FB176FE56346B3E3",
                            Rol = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "cocina@demo.local",
                            Nombre = "Cocina Demo",
                            PasswordHash = "7DBB7F051B44D7D54584A7BC6C32F00DA5A3B5E6973485B9FB176FE56346B3E3",
                            Rol = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "auxiliar@demo.local",
                            Nombre = "Auxiliar Demo",
                            PasswordHash = "7DBB7F051B44D7D54584A7BC6C32F00DA5A3B5E6973485B9FB176FE56346B3E3",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "direccion@demo.local",
                            Nombre = "Direccion Demo",
                            PasswordHash = "7DBB7F051B44D7D54584A7BC6C32F00DA5A3B5E6973485B9FB176FE56346B3E3",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("RolDestino")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("EventosDistribucion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "101",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 2,
                            Numero = "102",
                            Planta = "Planta 1"
                        },
                        new
                        {
                            Id = 3,
                            Numero = "201",
                            Planta = "Planta 2"
                        });
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipamientoEspecial")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Movilidad")
                        .HasColumnType("integer");

                    b.Property<bool>("NecesitaAyudaLevantarse")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.Property<int>("AlergiaId")
                        .HasColumnType("integer");

                    b.HasKey("ResidenteId", "AlergiaId");

                    b.HasIndex("AlergiaId");

                    b.ToTable("ResidenteAlergias");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("ResidenteDietas");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.EventoDistribucion", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Eventos")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Residentes")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteAlergia", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Alergia", "Alergia")
                        .WithMany()
                        .HasForeignKey("AlergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Alergias")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alergia");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.ResidenteDieta", b =>
                {
                    b.HasOne("Cuidexa.Web.Models.Dieta", "Dieta")
                        .WithMany()
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuidexa.Web.Models.Residente", "Residente")
                        .WithMany("Dietas")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Habitacion", b =>
                {
                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("Cuidexa.Web.Models.Residente", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Dietas");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
